### ISSUE TITLE
Can't find key bindingg

### ISSUE THREAD

**Issue by mildfuzz** [jmm/Sublime-Text-Block-Nav#1]
Could use a little help finding the relevant keybindings. Have looked in the user and default.

**Comment by iRonin** [comment]
You can find them [here](https://github.com/jmm/Sublime-Text-Block-Nav/blob/master/Packages/Block%20Nav/Default.sublime-keymap)

**Comment by jmm** [comment]
Thanks for your interest in the plugin, @mildfuzz, and sorry for the lack of response. The readme mentions to "See the keymap for bindings", but maybe that's asking for too much knowledge of the plugin architecture. I hope @iRonin's answer helped you -- thanks @iRonin. To be explicitly clear, at this time the default keybindings are:

"ctrl+shift+b", "up" : Up (north)

"ctrl+shift+b", "left" : Up and out (northwest)

"ctrl+shift+b", "down" : Down (south)

"ctrl+shift+b", "right" : Down and in (southeast)

Where up, left, down, and right refer to the arrow keys.
